services:
  db:
    image: mysql:8
    platform: linux/x86_64
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - ./db:/docker-entrypoint-initdb.d
      - mysql_data:/var/lib/mysql
    ports:
      - 3306:3306
    hostname: db

  app:
    build:
      context: app
    ports:
      - 8888:8888
      - 2345:2345
    volumes:
      - ./app:/app
    tty: true

volumes:
  mysql_data:
