name: lint
on:
  push:
    branches:
      - main

env:
  GO_VERSION: 1.23.5
  GOLANGCI_LINT_VERSION: 1.63.4

jobs:
  golangci-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Install golangci-lint
        run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@v${{ env.GOLANGCI_LINT_VERSION }}
      - name: Run golangci-lint
        run: golangci-lint run
        working-directory: ./app
